Added download and delete lessons and chapter support
chimple/cuba pull request #1015
Opened 2023-11-09 02:20 UTC by ALOK-TV

2023-11-09 03:24 UTC, bhanugummana requested changes

2023-11-09 03:24 UTC, bhanugummana commented on public/assets/icons/LessonCard.tsx
> +  }, [lesson]);
why do you need to get getCurrentCourse when ever lesson is changed??

2023-11-09 03:24 UTC, bhanugummana commented on public/assets/icons/LessonCard.tsx
> +      LESSON_CARD_COLORS[Math.floor(Math.random() * LESSON_CARD_COLORS.length)]
will this change to new color every time we side??

2023-11-09 03:24 UTC, bhanugummana commented on public/assets/icons/LessonCard.tsx
> +          height: "auto",
set this in css file

2023-11-09 03:24 UTC, bhanugummana commented on public/assets/icons/LessonCard.tsx
> +            display: "grid",
set this styles in css file

2023-11-09 03:24 UTC, bhanugummana commented on public/assets/icons/LessonCard.tsx
> +              from: history.location.pathname + "?continue=true",
take continue as a const from @mujafar7 PR

2023-11-09 03:24 UTC, bhanugummana commented on public/assets/icons/LessonCard.tsx
> +              display: "grid",
set this styles in css file

2023-11-09 03:24 UTC, bhanugummana commented on public/assets/icons/LessonCard.tsx
> +                  lesson.cocosSubjectCode +
go with the current course code, not with the cocosSubjectCode

2023-11-09 03:24 UTC, bhanugummana commented on src/components/DownloadLesson.tsx
> +    if (isStored(lessonID, "lessonItems")) {
use constants for lessonItems and chapterItems

2023-11-09 03:24 UTC, bhanugummana commented on src/components/DownloadLesson.tsx
> +  }, [lessonID, chapters]);
do we really need these dependencies??

2023-11-09 03:24 UTC, bhanugummana commented on src/components/DownloadLesson.tsx
> +    localStorage.setItem(storageKey, JSON.stringify(updatedItems));
check if this updatedItems is empty or null

2023-11-09 03:24 UTC, bhanugummana commented on src/components/DownloadLesson.tsx
> +          `Device is offline. Cannot download  ${
use i18n for this text

2023-11-09 03:24 UTC, bhanugummana commented on src/components/DownloadLesson.tsx
> +        await deleteLessons(chapters.id);
why are you doing the deleteLesson and other things in the setTimeout??

2023-11-09 03:24 UTC, bhanugummana commented on src/components/DownloadLesson.tsx
> +      case "success":
use this types as enum

2023-11-09 03:24 UTC, bhanugummana commented on src/utility/util.ts
> +  public static async checkDownloadedLessons() {
Don't check it every time the user opens the app; check after some time interval

2023-11-09 03:24 UTC, bhanugummana commented on src/utility/util.ts
> +    return true;
why is it returning true even whey delete failed

2023-11-09 03:24 UTC, bhanugummana commented on src/utility/util.ts
> +        storeId(folderNames[i].name, "lessonItems");
try to update the local storage all at once not on every loop

2023-11-09 03:24 UTC, bhanugummana commented on src/utility/util.ts
> +        localStorage.setItem(storageKey, JSON.stringify(updatedItems));
how are you removing the deleted lessonId from the localStorage

2023-11-09 03:24 UTC, bhanugummana commented on src/utility/util.ts
> +        );
how are you handling the localstorage for chapters

2023-11-20 03:49 UTC, Sutara-Skanda requested changes

2023-11-20 03:49 UTC, Sutara-Skanda commented on package.json
> +    "react-toastify": "^9.1.3",
use @capacitor/toast plugin instead react-toastify

2023-11-20 03:49 UTC, Sutara-Skanda commented on src/components/DownloadChapterAndLesson.css
> +.img {
don't use generic names anywhere

2023-11-20 03:49 UTC, Sutara-Skanda commented on src/components/DownloadChapterAndLesson.tsx
> +          className="delete"
same here

2023-11-24 10:06 UTC, Sutara-Skanda approved these changes

2023-12-11 05:01 UTC, bhanugummana approved these changes

2023-12-11 05:01 UTC, merged