Added an user friendly error message for default phone number errors …
chimple/cuba pull request #1029
Opened 2023-11-20 10:06 UTC by mujafar7

…from fire base
Image for the Issue
![1000084473](https://github.com/chimple/cuba/assets/134258437/b39892cb-09c2-474f-aa02-2483de38ee56)
Image after adding user friendly error message
![Screenshot_20231120_150740](https://github.com/chimple/cuba/assets/134258437/807b5fe3-591d-4cad-a93f-558026b83991)
![Screenshot_20231120_114010](https://github.com/chimple/cuba/assets/134258437/8a45d8e1-6486-4138-90cb-d4b510980d0f)

2023-11-20 11:13 UTC, Sutara-Skanda requested changes

2023-11-20 11:13 UTC, Sutara-Skanda commented on src/pages/Login.tsx
> +      alert(t("Resend Otp Failed!! You have entered the OTP incorrectly many times. Please try again after some time."));
put the all messages in constants page

2023-11-20 11:13 UTC, Sutara-Skanda commented on src/pages/Login.tsx
> +            alert("Phone Number signin Failed. Something went wrong. Please try again later.");
translate the error message

2023-11-20 11:13 UTC, Sutara-Skanda commented on src/pages/Login.tsx
> +            let errorMessage = "Phone Number signin Failed. Something went wrong. Please try again later.";
call alert in common way

2023-11-20 11:13 UTC, Sutara-Skanda commented on src/pages/Login.tsx
> +        if (typeof error === 'string') {
if possible get error code from error type and show the error message according to error code

2023-11-23 03:33 UTC, Sutara-Skanda approved these changes

2023-11-28 05:41 UTC, mujafar7 commented
![Screenshot_20231128_094448](https://github.com/chimple/cuba/assets/134258437/13e927a5-8b96-46bb-b4b7-93139f5c21f4)
![Screenshot_20231128_102326](https://github.com/chimple/cuba/assets/134258437/94a362bb-dc17-48a7-9ee0-6336a593b9ff)

2023-11-28 06:08 UTC, Sutara-Skanda approved these changes

2023-11-29 04:46 UTC, merged