Assign screen
chimple/cuba pull request #1418
Opened 2024-04-16 23:43 UTC by Mary-Harshitha

2024-04-17 03:38 UTC, bhanugummana requested changes
Add  screenshot of the sample UI

2024-04-17 03:38 UTC, bhanugummana commented on src/components/Malta/RecommendedAssignment.tsx
> +        These are the recommended assignments based on the previous assignments
Give i18n support for the text

2024-04-17 03:38 UTC, bhanugummana commented on src/components/Malta/RecommendedAssignment.tsx
> +        <div className="recommended-subject-header">
create multiple components

2024-04-17 03:38 UTC, bhanugummana commented on src/pages/Malta/Assignment.tsx
> +function CustomTabPanel(props: TabPanelProps) {
create components files

2024-04-23 04:15 UTC, bhanugummana requested changes
Rename the folder Malta -> malta

2024-04-23 04:15 UTC, bhanugummana commented on src/components/Malta/assignment/AssignButton.tsx
> +        display: "flex",
Add style in css  files

2024-04-23 04:15 UTC, bhanugummana commented on src/components/Malta/assignment/DisplayLesson.tsx
> +              <div className="lesson-icon-and-chapter-download-container">
Divide them into multiple components

2024-04-23 04:15 UTC, bhanugummana commented on src/components/Malta/assignment/RecommendedAssignment.tsx
> +                                flexDirection: "column",
Add style in css file

2024-04-23 04:15 UTC, bhanugummana commented on src/components/Malta/assignment/RecommendedAssignment.tsx
> +          lessons: [
Is this dummy data??

2024-04-23 04:17 UTC, Mary-Harshitha commented on src/components/Malta/assignment/RecommendedAssignment.tsx
> +          lessons: [
yes

2024-05-03 04:45 UTC, merged