UI for adding and removing User
chimple/cuba pull request #1419
Opened 2024-04-17 03:28 UTC by vinay961861

2024-04-17 03:41 UTC, bhanugummana requested changes
Add sample UI screenshot

2024-04-17 03:41 UTC, bhanugummana commented on src/components/userRoles/UserTabs.tsx
> +  value: string;
make value type as USERTYPES and rename the value

2024-04-17 03:52 UTC, vinay961861 commented
![Screenshot_20240417_092117](https://github.com/chimple/cuba/assets/62736791/0a0477c3-b014-491d-98ac-bc6ccc5adc95)

2024-04-17 03:54 UTC, vinay961861 commented
![Screenshot_20240417_092352](https://github.com/chimple/cuba/assets/62736791/3e1d7001-0f50-4df2-95da-50f3bc8a1e9b)

2024-04-17 03:56 UTC, vinay961861 commented
![Screenshot_20240417_092527](https://github.com/chimple/cuba/assets/62736791/d6ce469b-d158-451d-8310-261efeeaed47)

2024-04-22 06:41 UTC, vinay961861 commented
![Screenshot_20240422_121034](https://github.com/chimple/cuba/assets/62736791/973917e7-b5fe-4d0a-8edf-91fa80c09b70)
![Screenshot_20240422_121053](https://github.com/chimple/cuba/assets/62736791/68071f44-d9bf-4b9d-a608-2094c4f214a8)

2024-04-25 06:48 UTC, merged