fixed 14 character issues in parent screen in  completed
chimple/cuba pull request #383
Opened 2023-05-31 12:18 UTC by RakeshReddyVura

Completed fixed 14 character issues

2023-05-31 12:24 UTC, RakeshReddyVura commented
reopened the PR

2023-05-31 12:27 UTC, bhanugummana approved these changes

2023-06-01 04:07 UTC, RakeshReddyVura commented
Added the same logic for other pages

2023-06-01 04:14 UTC, Sutara-Skanda requested changes

2023-06-01 04:14 UTC, Sutara-Skanda commented on src/pages/Leaderboard.tsx
> +            <span id="currentStudent-name">{currentStudent?.name}</span>
Follow the naming convention for ids for everywhere like this **#page-name-element-appropriate-name**

2023-06-01 04:14 UTC, Sutara-Skanda commented on src/pages/Leaderboard.css
> +#currentStudent-name{
Follow the naming convention for ids for everywhere like this #page-name-element-appropriate-name

2023-06-01 04:25 UTC, RakeshReddyVura commented
Updated the logic with the naming convention

2023-06-01 04:27 UTC, Sutara-Skanda approved these changes

2023-06-01 04:49 UTC, merged