Fixed the school name in homework section also changed the headings in subject section.
chimple/cuba pull request #401
Opened 2023-06-05 09:42 UTC by Nikhil77sutara

2023-06-05 09:54 UTC, bhanugummana requested changes

2023-06-05 10:50 UTC, Nikhil77sutara commented on src/pages/Assignment.tsx
> +    api.getSchoolById(schoolId).then((res) => {
I resolved this issue.

2023-06-05 11:09 UTC, Nikhil77sutara commented on src/pages/Assignment.css
> +  margin-top: 2%;
I changes the font size from px to vh now it will work also removed the extra margin.

2023-06-05 11:13 UTC, bhanugummana requested changes

2023-06-05 11:13 UTC, bhanugummana commented on src/pages/Assignment.tsx
> +        api.getSchoolById(schoolId).then((res) => {
use await

2023-06-06 03:34 UTC, Nikhil77sutara commented on src/pages/Assignment.tsx
> +        api.getSchoolById(schoolId).then((res) => {
fixed the issue and using await

2023-06-06 03:52 UTC, bhanugummana approved these changes

2023-06-06 04:49 UTC, merged