Fixed that keyboard overlapping on okay button in Homework screen
chimple/cuba pull request #456
Opened 2023-06-15 07:26 UTC by renukaj07

2023-06-15 08:30 UTC, Sutara-Skanda approved these changes

2023-06-15 11:24 UTC, bhanugummana requested changes

2023-06-15 11:24 UTC, bhanugummana commented on src/components/assignment/JoinClass.tsx
> +  Util.isTextFieldFocus(scollToRef, setIsInputFocus)
Call this in useEffect

2023-06-16 07:19 UTC, renukaj07 commented on src/components/assignment/JoinClass.tsx
> +  Util.isTextFieldFocus(scollToRef, setIsInputFocus)
I changed that

2023-06-16 07:52 UTC, bhanugummana approved these changes

2023-06-16 07:54 UTC, merged