Added A New Score Card
chimple/cuba pull request #575
Opened 2023-07-08 06:41 UTC by mujafar7

2023-07-10 02:43 UTC, bhanugummana requested changes

2023-07-10 02:43 UTC, bhanugummana commented on src/pages/CocosGame.tsx
> +              yesText={"Like the Game" }
Add the text to translation json

2023-07-10 07:08 UTC, bhanugummana requested changes

2023-07-10 07:08 UTC, bhanugummana commented on src/components/parent/ScoreCard.tsx
> +const NewScoreCard: React.FC<{
where are you using this NewScoreCard.
if you are using it somewhere change the name to ScoreCard

2023-07-10 07:08 UTC, bhanugummana commented on src/components/parent/ScoreCard.tsx
> +            justifyContent: "space-around",
put this in css

2023-07-10 07:08 UTC, bhanugummana commented on src/components/parent/ScoreCard.tsx
> +              color: "black",
put this style in css file

2023-07-10 07:43 UTC, Sutara-Skanda commented on src/components/parent/ScoreCardStarIcons.tsx
> +const StarImages: React.FC<{
change the component name also. component and file name should match

2023-07-10 07:44 UTC, Sutara-Skanda requested changes
change the component name also. component and file name should match

2023-07-10 10:22 UTC, Sutara-Skanda approved these changes

2023-07-10 10:32 UTC, bhanugummana requested changes

2023-07-11 02:33 UTC, bhanugummana approved these changes

2023-07-11 09:44 UTC, Sutara-Skanda approved these changes

2023-07-11 12:00 UTC, merged