Added assignments into recommendations
chimple/cuba pull request #603
Opened 2023-07-12 11:32 UTC by Rahul-Chimple

2023-07-12 14:01 UTC, Sutara-Skanda requested changes
rename homework-icon to lesson-card-homework-icon

2023-07-13 02:35 UTC, bhanugummana requested changes

2023-07-13 02:35 UTC, bhanugummana commented on src/pages/Home.tsx
> +          allAssignments.push(...res);
Combine both getting assignments and getting lessons for assignments

2023-07-13 06:31 UTC, bhanugummana approved these changes

2023-07-13 06:49 UTC, Sutara-Skanda approved these changes

2023-07-13 07:11 UTC, merged