Subjects are  arranged in the order
chimple/cuba pull request #671
Opened 2023-07-24 08:39 UTC by ALOK-TV

2023-07-24 08:48 UTC, bhanugummana requested changes

2023-07-24 10:24 UTC, ALOK-TV commented on src/services/api/FirebaseApi.ts
> +        const digitalSkills = subjects.splice(2, 1)[0];
I'm using an if condition to check whether digital skills is present or not if digital skill is found then only  adding digital skills at the end

2023-07-24 11:29 UTC, bhanugummana requested changes

2023-07-24 11:29 UTC, bhanugummana commented on src/services/api/FirebaseApi.ts
> +      const digitaSkills = checkDigitalSkillSubject(subjects, 2);
sort once and use the code wherever required

2023-07-25 06:17 UTC, bhanugummana approved these changes

2023-07-25 06:17 UTC, merged