OTP input box not to allow special characters
chimple/cuba pull request #856
Opened 2023-09-01 07:32 UTC by RamReddyGowra

2023-09-01 07:40 UTC, Sutara-Skanda approved these changes

2023-09-01 09:39 UTC, bhanugummana approved these changes

2023-09-01 09:39 UTC, bhanugummana commented on src/pages/Login.tsx
> +                          const numberRegex = /^[0-9\b]+$/;
why are you using "\b" in this regex

2023-09-01 09:40 UTC, bhanugummana requested changes

2023-09-01 09:40 UTC, bhanugummana commented on src/pages/Login.tsx
> +                          const numberRegex = /^[0-9\b]+$/;
why are you using "\b" in this regex

2023-09-04 04:31 UTC, RamReddyGowra commented
I will create new PR

2023-09-04 04:31 UTC, closed without merging