Grades are Sorted in Subject Screen
chimple/cuba pull request #904
Opened 2023-09-13 17:24 UTC by mujafar7

2023-09-14 03:26 UTC, Sutara-Skanda requested changes

2023-09-14 03:26 UTC, Sutara-Skanda commented on src/common/constants.ts
>  export enum SL_GRADES {
rename the sl_Grades to Grades

2023-09-14 03:26 UTC, Sutara-Skanda commented on src/common/constants.ts
> +export const SL_GRADES_NUMERIC = {
same here also

2023-09-14 04:12 UTC, bhanugummana requested changes

2023-09-14 04:12 UTC, bhanugummana commented on src/common/constants.ts
> +  BELOWGRADE1 = "Below Grade 1",
Use Firebase doc ids instead of names...

2023-09-14 06:49 UTC, mujafar7 commented
<img width="941" alt="sorting grade ss" src="https://github.com/chimple/cuba/assets/134258437/c6a7d214-da84-476c-a8e5-023b8dd80c7b">

2023-09-15 07:12 UTC, bhanugummana approved these changes

2023-09-15 07:32 UTC, Sutara-Skanda approved these changes

2023-09-18 08:02 UTC, closed without merging