Designed and Developed home screen with new icons and features-Enhanc…
chimple/cuba pull request #936
Opened 2023-10-04 01:52 UTC by mujafar7

…ed Home Screen UI

![Screenshot_202310
![Screenshot_20231003_230602](https://github.com/chimple/cuba/assets/134258437/9f02b5fd-8c1e-41f2-b6e9-6896a0953418)

![Screenshot_20231003_231039](https://github.com/chimple/cuba/assets/134258437/e502c0d8-5b55-4a78-bdf5-14fd9c1aae8d)
![Screenshot_20231003_230611](https://github.com/chimple/cuba/assets/134258437/aed5b5f1-4fe5-4c3a-8495-1e96ce06bc9b)
![Screenshot_20231003_230621](https://github.com/chimple/cuba/assets/134258437/19096a13-2eb7-4f68-ba90-a217f1fe839f)
![Screenshot_20231003_230604](https://github.com/chimple/cuba/assets/134258437/8b58f712-4aa1-4e5e-9082-4a4382223cd3)
![Screenshot_20231003_230559](https://github.com/chimple/cuba/assets/134258437/8b92eca4-9f51-4530-958c-cc06e2a71154)
![Screenshot_20231003_230555](https://github.com/chimple/cuba/assets/134258437/8bb7d0a3-2f8c-433b-b382-c1f51b99a09f)
![Screenshot_20231003_230551](https://github.com/chimple/cuba/assets/134258437/7818f973-e973-4ad1-801a-a1bec64a95d4)
![Screenshot_20231003_231055](https://github.com/chimple/cuba/assets/134258437/92a1360d-11eb-46b4-a079-efa3d31e7ad4)

2023-10-04 03:14 UTC, bhanugummana requested changes

2023-10-04 03:14 UTC, bhanugummana commented on src/pages/DisplayChapters.tsx
> +      onCourseChanges(getCourseByUrl);
why do you need this in useEffect??

2023-10-04 03:14 UTC, bhanugummana commented on src/pages/DisplayChapters.tsx
> +    getLocalGradeMap();
try to avoid using multiple useEffects

2023-10-04 08:14 UTC, mujafar7 commented
![Screenshot_20231004_134052](https://github.com/chimple/cuba/assets/134258437/4b91d80d-294e-48fa-87f9-da1c274ba076)
![Screenshot_20231004_134047](https://github.com/chimple/cuba/assets/134258437/9a71b8d6-009c-478d-9c86-6a58ae4da6e7)

2023-10-04 09:03 UTC, Sutara-Skanda requested changes

2023-10-04 09:03 UTC, Sutara-Skanda commented on src/components/displaySubjects/SelectCourse.tsx
> +              style={{
move css style to selectCouse.css file

2023-10-04 09:03 UTC, Sutara-Skanda commented on src/pages/Home.tsx
> +  useEffect(() => {
use single useEffect

2023-10-05 10:40 UTC, Sutara-Skanda approved these changes

2023-10-06 04:48 UTC, merged